---
# Note that global facts are part of the public interface of the role
# Values for existing definitions cannot be refactored/removed

- name: Set global facts
  ansible.builtin.set_fact:
    _postgresql_package_all: "{{ _package_server + _package_client }}"
    _postgresql_package_server: "{{ _package_server }}"
    _postgresql_package_client: "{{ _package_client }}"
    _postgresql_package_extra: "{{ postgresql_package_extra | default(_default_package_extra) }}"
    _postgresql_service_name: "{{ postgresql_service_name | default(_default_service) }}"
    _postgresql_user: "{{ postgresql_user }}"
    _postgresql_group: "{{ postgresql_group }}"
    _postgresql_confdir: "{{ _conf_confdir }}"
    _postgresql_datadir: "{{ _conf_datadir }}"
    _postgresql_bindir: "{{ _conf_bindir }}"
    _postgresql_socketdir: "{{ _conf_socketdir }}"
    _postgresql_initdb: "{{ postgresql_initdb }}"
    _postgresql_auth_method: "{{ _auth_method }}"
    _postgresql_pgoptions: "{{ (_auth_method == _auth_scram_sha256) | ternary(_auth_scram_option, '') }}"
    _postgresql_conf_includedir: "{{ _conf_includedir }}"
    _postgresql_conf_main_manage: "{{ postgresql_conf_main_manage | default(True) }}"
    _postgresql_conf_hba_manage: "{{ postgresql_conf_hba_manage | default(True) }}"
    _postgresql_conf_ident_manage: "{{ postgresql_conf_ident_manage | default(True) }}"
    _postgresql_conf_main: "{{ _conf_confdir }}/{{ postgresql_conf_main_file | default('postgresql.conf') }}"
    _postgresql_conf_ident: "{{ _conf_confdir }}/{{ postgresql_conf_ident_file | default('pg_ident.conf') }}"
    _postgresql_conf_hba: "{{ _conf_confdir }}/{{ postgresql_conf_hba_file | default('pg_hba.conf') }}"
    _postgresql_conf_socket: "{{ postgresql_conf_socketdir_manage | bool }}"
    _postgresql_conf_ansible_file: "{{ _conf_includedir }}/{{ __postgresql_conf_ansible_file }}"
    _postgresql_conf_exclude: "{{ __postgresql_conf_exclude }}"
    _postgresql_conf_search: "{{ _conf_search }}"
    _postgresql_databases: "{{ _databases }}"
    _postgresql_roles: "{{ _roles }}"
  vars:
    _default_package_server: "{{ __postgresql_package_server | nephelaiio.plugins.sorted_get(_conf_search) }}"
    _default_package_client: "{{ __postgresql_package_client | nephelaiio.plugins.sorted_get(_conf_search) }}"
    _default_package_extra: "{{ __postgresql_package_extra | nephelaiio.plugins.sorted_get(_conf_search) }}"
    _default_service: "{{ __postgresql_service_name | nephelaiio.plugins.sorted_get(_conf_search) }}"
    _default_database:
      state: present
    _default_roles:
      state: present
    _package_server: "{{ postgresql_package_server | default(_default_package_server) }}"
    _package_client: "{{ postgresql_package_client | default(_default_package_client) }}"
    _conf_confdir: "{{ __postgresql_conf_dir }}"
    _conf_datadir: "{{ __postgresql_datadir | nephelaiio.plugins.sorted_get(_conf_search) }}"
    _conf_bindir: "{{ __postgresql_bindir | nephelaiio.plugins.sorted_get(_conf_search) }}"
    _conf_socketdir: "{{ __postgresql_socketdir | nephelaiio.plugins.sorted_get(_conf_search) }}"
    _conf_search: "{{ __postgresql_os_search }}"
    _conf_includedir: "{{ _conf_confdir }}/conf.d"
    _auth_scram_sha256: "scram-sha-256"
    _auth_scram_option: "-c password_encryption={{ _auth_scram_sha256 }}"
    _auth_method: "{{ postgresql_auth_method }}"
    _databases: "{{ [_default_database] | product(postgresql_databases) | map('combine') }}"
    _roles: "{{ [_default_roles] | product(postgresql_roles) | map('combine') }}"
