---
__postgresql_os_search:
  - "{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}"
  - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}"
  - "{{ ansible_distribution | lower }}"
  - "{{ ansible_os_family | lower }}"
  - "default"
__postgresql_package_extra:
  redhat:
    - "python3-dnf-plugin-versionlock"
    - "glibc-langpack-{{ postgresql_locale | regex_replace('_.*', '') }}"
  debian:
    - "pgtop"
    - "pg-activity"
__postgresql_package_server:
  redhat:
    - "postgresql{{ postgresql_release }}-server"
    - "postgresql{{ postgresql_release }}-contrib"
  debian:
    - "postgresql-{{ postgresql_release }}"
__postgresql_package_client:
  redhat:
    - "postgresql{{ postgresql_release }}"
  debian:
    - "postgresql-client-{{ postgresql_release }}"

__postgresql_bindir:
  redhat: "/usr/pgsql-{{ postgresql_release }}/bin"
  debian: "/usr/lib/postgresql/{{ postgresql_release }}/bin"
__postgresql_datadir:
  redhat: "/var/lib/pgsql/{{ postgresql_release }}/main/data"
  debian: "/var/lib/postgresql/{{ postgresql_release }}/main"
__postgresql_socketdir:
  redhat: "/run/postgresql"
  debian: "/var/run/postgresql"
