---
postgresql_release: 16
postgresql_pip_state: present
postgresql_pip_manage: true
postgresql_package_state: present
postgresql_service_state: started
postgresql_service_enabled: true
postgresql_service_masked: false
postgresql_user: postgres
postgresql_group: postgres
postgresql_waldir: "/var/lib/postgresql/wal"
postgresql_datadir: "/var/lib/postgresql/data"
postgresql_roles: []
postgresql_databases: []
postgresql_auth_method: md5  # [ scram-sha-256 | md5 ]
postgresql_default_database: postgres
postgresql_locale: en_US.UTF-8
postgresql_hba_entries: []
