---
name: lint

env:
  DEVBOX_VERSION: ${{ vars.DEVBOX_VERSION }}

on:
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: "nephelaiio.postgresql"

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4
        with:
          path: "nephelaiio.postgresql"

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          project-path: "nephelaiio.postgresql"

      - name: Lint code
        run: devbox run -- make lint
