---
name: molecule

on:
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: "nephelaiio.postgresql"

jobs:
  molecule:
    name: molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - deploy
          - stop
          - mask
          - databases
          - configure
          - initdb
          - hold
        image:
          - name: ubuntu2404
            command: /lib/systemd/systemd
          - name: ubuntu2204
            command: /lib/systemd/systemd
          - name: debian12
            command: /lib/systemd/systemd
          - name: debian11
            command: /lib/systemd/systemd

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4
        with:
          path: "nephelaiio.postgresql"

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.14.0
        with:
          project-path: "nephelaiio.postgresql"
          enable-cache: true

      - name: Install dependencies
        run: devbox run -- make install

      - name: Run molecule tests.
        run: devbox run -- make test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DOCKER_IMAGE: ${{ matrix.image.name }}
          MOLECULE_DOCKER_COMMAND: ${{ matrix.image.command }}
          MOLECULE_SCENARIO: ${{ matrix.scenario }}
